DROP TABLE IF EXISTS transactions;
DROP TABLE IF EXISTS

CREATE TABLE transactions (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    detail TEXT NOT NULL,
    amount INTEGER NOT NULL
);

CREATE TABLE data (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    rate INTEGER NOT NULL,
    currentbal INTEGER NOT NULL,
    lastupdate TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);